# ORIGINAL FILE: https://github.com/mtransitapps/commons/tree/master/shared-overwrite
name: MT Store (enable/disable channels)
on:
  workflow_dispatch: # manual
    inputs:
      alpha-enable:
        description: 'Enable releases to `Alpha` channel'
        type: boolean
        default: false
        required: false
      alpha-disable:
        description: 'Disable releases to `Alpha` channel'
        type: boolean
        default: false
        required: false
      beta-private-enable:
        description: 'Enable releases to `Beta Private` channel'
        type: boolean
        default: false
        required: false
      beta-private-disable:
        description: 'Disable releases to `Beta Private` channel'
        type: boolean
        default: false
        required: false
      production-enable:
        description: 'Enable releases to `Production` channel'
        type: boolean
        default: false
        required: false
      production-disable:
        description: 'Disable releases to `Production` channel'
        type: boolean
        default: false
        required: false
# gh workflow run mt-store-channels.yml --ref $(git rev-parse --abbrev-ref HEAD)
# gh workflow run mt-store-channels.yml -f production-disable=true
# gh run list --workflow=mt-store-channels.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  MT_BOT_USER_NAME: ${{ vars.MT_BOT_USER_NAME }}
  MT_BOT_USER_EMAIL: ${{ vars.MT_BOT_USER_EMAIL }}
  # git branches & sha
  MT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  MT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  MT_TARGET_BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  MT_DEFAULT_BRANCH_NAME: ${{ github.event.repository.default_branch }}
  # repo type
  MT_IS_SUBMODULE: ${{ contains(fromJSON('["mtransitapps/commons", "mtransitapps/commons-java", "mtransitapps/parser", "mtransitapps/commons-android"]'), github.repository) }}
  MT_IS_MAIN_REPO: ${{ endsWith(github.repository, '/mtransit-for-android') }}
  MT_IS_AGENCY_REPO: ${{ ! contains(fromJSON('["mtransitapps/commons", "mtransitapps/commons-java", "mtransitapps/parser", "mtransitapps/commons-android"]'), github.repository) && ! endsWith(github.repository, '/mtransit-for-android')}}
  MT_IS_AGENCY_RDS: ${{ ! contains(github.repository, '-bike-') }}
  MT_IS_AGENCY_BIKE: ${{ contains(github.repository, '-bike-') }}
  # git commit & push
  MT_ORG_GIT_COMMIT_ON: ${{ secrets.MT_ORG_GIT_COMMIT_ON }}
  MT_ORG_GIT_COMMIT_OFF: ${{ secrets.MT_ORG_GIT_COMMIT_OFF }}
  MT_GIT_COMMIT_ON: ${{ secrets.MT_GIT_COMMIT_ON }}
  MT_GIT_COMMIT_OFF: ${{ secrets.MT_GIT_COMMIT_OFF }}
jobs:
  MT-STORE-CHANNELS-JOB:
    name: "MT Store channels"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: MT check out main repository code (no submodules)
        uses: actions/checkout@v6
        with:
          submodules: true # required to set right token
          token: ${{ secrets.MT_PAT }}
          fetch-depth: 0 # fetch all (not required util release build)

      # - name: MT setup
      #   id: mt-setup
      #   uses: ./.github/actions/setup

      - name: MT Enable `Alpha` channel
        if: ${{ github.event.inputs.alpha-enable == 'true' }}
        run: |
          mkdir -p config/store/
          touch config/store/alpha
      - name: MT Disable `Alpha` channel
        if: ${{ github.event.inputs.alpha-disable == 'true' }}
        run: |
          rm -f config/store/alpha

      - name: MT Enable `Beta Private` channel
        if: ${{ github.event.inputs.beta-private-enable == 'true' }}
        run: |
          mkdir -p config/store/
          touch config/store/beta-private
      - name: MT Disable `Beta Private` channel
        if: ${{ github.event.inputs.beta-private-disable == 'true' }}
        run: |
          rm -f config/store/beta-private

      - name: MT Enable `Production` channel
        if: ${{ github.event.inputs.production-enable == 'true' }}
        run: |
          mkdir -p config/store/
          touch config/store/production
      - name: MT Disable `Production` channel
        if: ${{ github.event.inputs.production-disable == 'true' }}
        run: |
          rm -f config/store/production

      - name: MT Commit changes
        run: |
          git config user.name "$MT_BOT_USER_NAME"
          git config user.email "$MT_BOT_USER_EMAIL"
          git add -v config/store
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          BRANCH_NAME="update_store_channels"
          git checkout -B "$BRANCH_NAME"
          git commit -m "Update store channels"
          git push -u origin "$BRANCH_NAME" --force

      - name: MT Create pull request (if necessary)
        run: |
          # if local branch is update_store_channels, create PR
          CURRENT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [ $CURRENT_BRANCH_NAME == 'update_store_channels' ]; then
            if ! gh pr view update_store_channels >/dev/null 2>&1; then
              gh pr create --fill
            else
              echo "A pull request for branch 'update_store_channels' already exists."
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.MT_PAT }}

      # - name: MT push commits
      #   run: ./push_commits.sh
      #   env:
      #     GH_TOKEN: ${{ secrets.MT_PAT }}